// <auto-generated />
// This file is generated automatically by Entity Framework Core.
// It represents the final database model after applying migrations.

using System; // Provides basic .NET types (e.g., DateTime)
using Microsoft.EntityFrameworkCore; // EF Core main components
using Microsoft.EntityFrameworkCore.Infrastructure; // EF Core infrastructure
using Microsoft.EntityFrameworkCore.Migrations; // Migration-related attributes
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; // Value converters
using OexaDentalClinic.Api.Data; // Application DbContext

#nullable disable // Disables nullable reference warnings for this file

namespace OexaDentalClinic.Api.Data.Migrations
{
    // Specifies which DbContext this migration belongs to
    [DbContext(typeof(AppDbContext))]

    // Unique identifier for this migration (timestamp + name)
    [Migration("20260129213700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        // Builds the target EF Core model snapshot
        // EF Core uses this to compare schema changes between migrations
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Adds metadata about EF Core and database limits
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2") // EF Core version
                .HasAnnotation("Relational:MaxIdentifierLength", 64); // MySQL identifier length

            // Defines the Appointment entity mapping
            modelBuilder.Entity("OexaDentalClinic.Api.Models.Appointment", b =>
                {
                    // Primary key column
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd() // Auto-increment
                        .HasColumnType("int");

                    // Optional notes column
                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longtext");

                    // Record creation timestamp
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    // Email column (required, max 150 chars)
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    // First name column (required, max 100 chars)
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    // Last name column (required, max 100 chars)
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    // Phone number column (required, max 50 chars)
                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    // Preferred appointment date and time
                    b.Property<DateTime>("PreferredDateTime")
                        .HasColumnType("datetime(6)");

                    // Requested service column (required, max 150 chars)
                    b.Property<string>("ServiceNeeded")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    // Defines primary key
                    b.HasKey("Id");

                    // Maps this entity to the Appointments table
                    b.ToTable("Appointments");
                });
#pragma warning restore 612, 618  //t re-enables compiler warnings with codes 612 and 618 after they were previously disabled.
        }
    }
}


// This file is auto-generated
// It is called a Model Snapshot
// EF Core uses it to:
// Track schema state
// Detect future changes
// Generate new migrations
// You should not edit this file manually

// Migration = “steps to change schema”
// Snapshot = “current schema model reference”

// EF does not compare “database vs code” when creating migrations.
// It compares snapshot vs current code model.

// Which files are safe to modify (and which are not)
// Edit entities and DbContext; avoid editing snapshots; migrations only if necessary.