// <auto-generated />
// This file is generated automatically by Entity Framework Core.
// It stores the "latest known model state" after the most recent migration.
// EF uses it to compare against your current C# model to generate the next migration.

using System; // Provides DateTime type
using Microsoft.EntityFrameworkCore; // EF Core model builder
using Microsoft.EntityFrameworkCore.Infrastructure; // ModelSnapshot base class and EF infrastructure
using Microsoft.EntityFrameworkCore.Storage.ValueConversion; // Value converters (not always used directly here)
using OexaDentalClinic.Api.Data; // Your AppDbContext reference

#nullable disable // Disables nullable reference warnings for this file

namespace OexaDentalClinic.Api.Data.Migrations
{
    // Specifies that this snapshot belongs to AppDbContext
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // EF calls this method to rebuild the model definition in memory
        // This represents the schema state AFTER the latest migration
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Adds metadata about EF Core version and relational constraints
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2") // EF Core version used when snapshot was generated
                .HasAnnotation("Relational:MaxIdentifierLength", 64); // MySQL identifier length limit

            // Defines the Appointment entity mapping (table + columns)
            modelBuilder.Entity("OexaDentalClinic.Api.Models.Appointment", b =>
                {
                    // Primary key column: Id (auto-generated on insert)
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Optional column: AdditionalNotes (text)
                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longtext");

                    // CreatedAt column (datetime with microseconds precision)
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    // Required column: Email, max length 150
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    // Required column: FirstName, max length 100
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    // Required column: LastName, max length 100
                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    // Required column: PhoneNumber, max length 50
                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    // PreferredDateTime column (datetime)
                    b.Property<DateTime>("PreferredDateTime")
                        .HasColumnType("datetime(6)");

                    // Required column: ServiceNeeded, max length 150
                    b.Property<string>("ServiceNeeded")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    // Declares Id as primary key
                    b.HasKey("Id");

                    // Maps Appointment entity to the "Appointments" table
                    b.ToTable("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}


// This is the schema reference EF Core stores.
// When you change your model (Appointment.cs or AppDbContext), EF compares:
// Current model vs this snapshot
// Then it generates a new migration for the differences.
// You should not edit this snapshot manually.
// Instead: edit your entities/DbContext, then run dotnet ef migrations add 